### ISSUE TITLE
Misspell in README

### ISSUE THREAD

**Issue by stromperton** [damnedpie/godot-appodeal-3.x.x#2]
> Make sure to open your Godot project, go to Project -> Settings and add a new "Appodeal/**App**Key" property (String). Store your Appodeal AppKey inside this property and reference it via ProjectSettings.get_setting("Appodeal/**Api**Key").

**Comment by damnedpie** [comment]
It's not a misspell, really. Appodeal calls this string an "Application Key", so it's an AppKey. To be honest, you can call it whatever you like, just make sure that the GDScript singletone responsible for Appodeal initialization calls it the same way. Like:
`initialize(ProjectSettings.get_setting("Appodeal/WhateverYouWannaCallMe"), AdType.INTERSTITIAL|AdType.REWARDED_VIDEO)`

UPD: Ah, I see what you meant. I have fixed the misspell, thanks a lot.
