### ISSUE TITLE
Does Appodeal show GDPR/CCPA automatically or should I show it? If yes, how do i do it?
Thank you.

### ISSUE THREAD

**Issue by Momo90k** [damnedpie/godot-appodeal-3.x.x#4]

**Comment by damnedpie** [comment]
Hi! Sorry for long reply, haven't looked into this repo's issues for a while. Yes, Appodeal would show a Consent Screen automatically depending on the region. If GDPR or CCPA compliance are not required in a region, the Consent Screen wouldn't be shown.
